name: Test contracts

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  static-code-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    if: github.actor != 'secured-finance-machine-user[bot]'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install Dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run check:prettier
      - name: Run ESLint
        run: npm run check:lint
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    if: github.actor != 'secured-finance-machine-user[bot]'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install Dependencies
        run: npm ci
      - name: Run Unit Tests
        run: npm run test
