name: Upgrade Contracts

on:
  workflow_dispatch:
    inputs:
      upgrade_contracts:
        description: 'Contracts to upgrade (comma-separated)'
        required: true
        type: string
      network:
        description: 'Network'
        required: true
        default: 'testnet'
        type: choice
        options:
          - testnet
          - mainnet

jobs:
  upgrade:
    name: Upgrade Contracts
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ (github.event.inputs.network == 'testnet' && 'develop') || 'main' }}
          token: ${{ steps.generate_token.outputs.token }}
      - name: 'Setup for git'
        run: |
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm ci
      - name: Build Smart Contracts
        run: npm run compile
      - name: Upgrade Contracts
        env:
          UPGRADE_CONTRACTS: ${{ github.event.inputs.upgrade_contracts }}
        run: |
          npx hardhat run --network ${{ github.event.inputs.network }} deployments/upgrade-contracts.js
          git add .
      - name: Check diff
        shell: bash
        id: diff
        run: |
          echo "count=$(git diff --staged --name-only . | wc -l)" >> $GITHUB_OUTPUT
      - name: Commit and push
        shell: bash
        if: ${{ steps.diff.outputs.count > 0 }}
        run: |
          git commit -m "chore: upgrade contracts [SF-1426]" --no-verify
          git push
      - name: Merge main into develop
        shell: bash
        if: ${{ github.event.inputs.network != 'testnet' }}
        run: |
          git switch develop
          git merge main --no-verify
          git push
